version: "3.7"

services:

  mysql:
    container_name: apollo-work-mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/ddl:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test_db
      TZ: 'Asia/Tokyo'

  redis:
    container_name: apollo-work-redis
    image: redis:5
    ports:
      - "6379:6379"

  # dynamodb:
  #   container_name: apollo-work-dynamodb
  #   image: amazon/dynamodb-local
  #   ports:
  #     - 8000:8000
  #   command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
  #   volumes:
  #     - ./dynamoData:/data
